### ISSUE TITLE
aliases

### ISSUE THREAD

**Issue by ligi** [ligi/FAST#50]
add alias functionality sometimes the user wants another name for the app then the developer - this could bridge this gap

**Comment by iamale** [comment]
This one would really be awesome. I've posted a small bounty for it: [![Bountysource](https://www.bountysource.com/badge/issue?issue_id=4354818)](https://www.bountysource.com/issues/4354818-aliases?utm_source=4354818&utm_medium=shield&utm_campaign=ISSUE_BADGE)

I could help with code, but unfortunately I'm no good at Android development :(

**Comment by SebiderSushi** [comment]
I'm implementing this right now.
Does 'alias' mean just renaming or also creating additional entries?

**Comment by ligi** [comment]
Nice! Was thinking about additional entries back then

**Comment by SebiderSushi** [comment]
It's implemented in commit 2529bee5f20e30c4a432160ae22fafcb9fd6fb4b  (and included in my pull request #91 which is, by now, quite crowded tough).
Everything worked for me. Check if you have any abjections towards how I did it or if you can find any bugs.
As of now the changes clash together with af0dcf0f44148347fcd4400d463815382d037e2f (Hide and Pin mode) but if you don't want to incorporate these changes I'm willing to make my aliasing commit fit right onto your currrent master.
