### ISSUE TITLE
Can't add newly installed apps without resetting usage history

### ISSUE THREAD

**Issue by rstarkov** [ligi/FAST#61]
"Sort by usage" is pretty cool, in theory, but it only lasts until the next time I install a new app. The only way I know of to make FAST show the new app is to "Clear cache", which also wipes the usage history.

It would be really cool if there was a way to scan for new apps without resetting usage history.

**Comment by ligi** [comment]
this bug is fixed in the latest beta ( 6.0 ) and I hope to roll it out to public soon - thanks for reporting!
