### ISSUE TITLE
Pin app

### ISSUE THREAD

**Issue by rstarkov** [ligi/FAST#62]
I'm using FAST as a home screen replacement and one thing that I miss is the ability to pin some apps to always appear at the top.

Suggestion: add an option to the long tap menu to pin or unpin an app. The only effect this needs to have is to always sort pinned apps before unpinned apps. To keep things simple, I think it's even acceptable if the pinned apps are sorted the same way as the unpinned ones, without any way of reordering them manually.

**Comment by ligi** [comment]
Now in v6.7 via PR of @SebiderSushi
