### ISSUE TITLE
Move Help icon to settings

### ISSUE THREAD

**Issue by emersion** [ligi/FAST#78]
Makes more sense to show it in settings instead of the app list header.

**Comment by ligi** [comment]
can you elaborate? I do not understand

**Comment by emersion** [comment]
Remove the <kbd>?</kbd> icon in the toolbar, like on this screenshot:
![](https://lh3.ggpht.com/hy3dDgCBbOEPOoZY6dSij8q1cXeqlOgGoht9905wwmKxO0oOQh-vvXVtqRKD0_h1uSqK=h900)

**Comment by ligi** [comment]
OK but why? Makes the help hard to find and I do not see that you need this space - usually you enter only <5 chars in the edittext ..

**Comment by iamale** [comment]
@ligi Less visual clutter this way.

**Comment by ligi** [comment]
Yea but less discoverability also and the context is wrong then - it is not help for settings - it is help for the app - really unsure about this change

**Comment by iamale** [comment]
I suppose you could just show it on the first launch? With a line like “You can always find this help in <...>”.
Also you can probably use the “three dots” overflow menu (with two items — Settings / Help; probably also you could add About)

**Comment by ligi** [comment]
In FASTER there is no more help - so also no help button - think this solves this issue
