### ISSUE TITLE
Release FASTER to F-droid, Amazon Appstore, &c (& more regularly to Google Play)

### ISSUE THREAD

**Issue by TPS** [ligi/FAST#82]
I'm not sure but FASTER is a manually created APK (simply with stuff taken out by hand), but it probably should have its own build recipe that F-droid, &c can use for releases automagically, like what seems to happen with FAST itself.  If done well,  maybe this will cut down on that manual production, while keeping everything updated & released well.

**Comment by ligi** [comment]
FASTER is a flavor of FAST ( https://github.com/ligi/FAST/blob/master/android/build.gradle#L53 )

**Comment by TPS** [comment]
So, I mean just to have it released to all the other platforms as often as to Google Play, & have it updated to all of the above as often as FAST itself is.

Thanks!

**Comment by ligi** [comment]
No - releasing is some manual work for amazon and play - stopped Amazon completely because of this. FDroid will always be the fastest and Play will follow

**Comment by TPS** [comment]
I understand.  Thanks!

**Comment by TPS** [comment]
@ligi I don't know whether I tagged your GitLab username correctly, but [the F-Droid RFP](https://gitlab.com/fdroid/rfp/issues/597) could probably use your input.
