### ISSUE TITLE
Please release v6.4 to GPlay

### ISSUE THREAD

**Issue by TPS** [ligi/FAST#84]
@ligi It's been several months since v6.4 has been released to F-droid.  [Could it be released to Google Play?](https://github.com/ligi/FAST/commit/352c0ee946d23b22f76358d5fd2c3a5503a22000#commitcomment-12258062)

Thanks!

**Comment by ligi** [comment]
Thanks for the reminder - just uploaded it to the beta-section of play

**Comment by ligi** [comment]
and switched to open-beta: https://play.google.com/apps/testing/org.ligi.fast

**Comment by TPS** [comment]
Thanks! I just got the FAST update. ☺ Could we get FASTER, also? :pray:
