### ISSUE TITLE
Replace Appdrawer instead of Homescreen

### ISSUE THREAD

**Issue by tobimensch** [ligi/FAST#85]
Hi,

I love this app, great work!

Yet I want to keep using a couple of widgets I had on my traditional homescreen.

Could you add an option to this app, so that it replaces the app drawer instead
of the whole launcher?

That way it would be possible to use the best of both worlds.

Kind regards.

**Comment by ligi** [comment]
AFAIK this is not possible - but you can use it via the ASSIST intent ( google now ) and keep your appdrawer this way - Or just have fast icon on the homescreen
