### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by tobimensch** [ligi/FAST#86]
Hi,

I think it would be a great feature if it was possible to blacklist apps.

For example when long-clicking on apps there could be an additional entry in the popup menu
"Blacklist this app", which would make it disappear from the list and in searches.

There are some system apps for example that I'm never going to use and they sometimes show
up in searches and annoy me in doing so. :-)

Of course there would also need to be an option in the settings to include blacklisted apps in searches, so that you could unblacklist them again.

Kind regards.

**Comment by SebiderSushi** [comment]
(This can now also be closed.)
