### ISSUE TITLE
Problems with adaptive icons on Android-O

### ISSUE THREAD

**Issue by ligi** [ligi/FAST#92]

**Comment by cketti** [comment]
`ResolveInfo.loadIcon()` returns an `AdaptiveIconDrawable` instance for adaptive icons. That will lead to a `ClassCastException` here:

https://github.com/ligi/FAST/blob/204373e582a0d70203a62ae30e9f3d2e408891ce/android/src/main/java/org/ligi/fast/model/AppIconCache.java#L91
